### ISSUE TITLE
STATSGO sometimes extracts NA for matricd only

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/rSFSW2#93]
I'm running the 36 validation sites, and for two of them (CA_Blo, OR_Me2), STATSGO extracts a value of NA for matricd for all layers, but has data for sand, clay, and gravel.

Should a dummy value be placed there in the case of NA (e.g. 1.0), or should we let the sites fail? Additionally, should STATSGO be lacking data in the first place?

Thanks

**Comment by dschlaep** [comment]
We are not using the STATSGO dataset directly; instead, we are using a derived product: the gridded CONUS-Soil (Miller, Douglas A., and Richard A. White. 1998. A Conterminous United States Multilayer Soil Characteristics Dataset for Regional Climate and Hydrology Modeling. Earth Interactions 2, 2: 1–26).

The CONUS-Soil dataset contains cells with no data, e.g., http://www.soilinfo.psu.edu/index.cgi?soil_data&conus&data_cov&bd&image

The code should be set up to fail and this is intended. I am vehemently against making up dummy/fake data. Even if it means that it is inconvenient because a project needs human intervention to run.
